name: CellPilot-dev
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cfitsio=3.470
  - charls=2.2.0
  - click=8.1.8
  - cloudpickle=3.1.1
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.1
  - dask-core=2024.8.0
  - dav1d=1.2.1
  - freetype=2.13.3
  - fsspec=2025.3.2
  - gettext=0.21.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.2
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - importlib_metadata=8.6.1
  - importlib_resources=6.4.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - llvm-openmp=20.1.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.4
  - networkx=3.2.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - packaging=24.2
  - partd=1.4.2
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - ply=3.11
  - pybind11-abi=4
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pytorch=2.2.2
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.32.3
  - s_gd2=1.8.1
  - scikit-image=0.19.3
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.7.8
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tifffile=2024.6.18
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.4.2
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.1
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - anndata==0.10.9
      - annotated-types==0.7.0
      - anyio==4.9.0
      - array-api-compat==1.11.2
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - beautifulsoup4==4.13.3
      - biopython==1.85
      - boltons==25.0.0
      - cellphonedb==5.0.1
      - charset-normalizer==3.4.1
      - chord==6.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - ctxcore==0.2.0
      - cycler==0.12.1
      - datetime==5.5
      - decorator==5.2.1
      - deprecated==1.2.18
      - dill==0.3.9
      - drawsvg==2.4.0
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.12
      - fbpca==1.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - formulaic==1.1.1
      - frozendict==2.4.6
      - frozenlist==1.5.0
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - geosketch==1.3
      - get-annotations==0.1.2
      - git-filter-repo==2.47.0
      - google-pasta==0.2.0
      - graphtools==1.5.3
      - grpcio==1.71.0
      - gtfparse==2.5.0
      - h11==0.16.0
      - h5py==3.13.0
      - harmonypy==0.0.10
      - httptools==0.6.4
      - huggingface-hub==0.30.1
      - idna==3.10
      - igraph==0.11.8
      - infercnvpy==0.4.5
      - iniconfig==2.1.0
      - interface-meta==1.3.0
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jupyterlab-widgets==3.0.13
      - keras==3.9.2
      - kiwisolver==1.4.7
      - ktplotspy==0.2.4
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - libclang==18.1.1
      - lifelines==0.30.0
      - llvmlite==0.43.0
      - louvain==0.8.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - metatime==1.3.0
      - mizani==0.9.3
      - ml-dtypes==0.5.1
      - mofax==0.3.7
      - multidict==6.2.0
      - multiprocess==0.70.17
      - namex==0.0.9
      - narwhals==1.33.0
      - natsort==8.4.0
      - numba==0.60.0
      - numpy-groupies==0.11.2
      - nvidia-ml-py==12.570.86
      - omicverse==1.6.10
      - openchord==0.1.7
      - opt-einsum==3.4.0
      - optree==0.15.0
      - palettable==3.3.3
      - pandas==2.2.3
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - plotly==6.0.1
      - plotnine==0.12.4
      - pluggy==1.5.0
      - polars==0.20.31
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==14.0.2
      - pycomplexheatmap==1.8.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydeseq2==0.4.12
      - pygam==0.8.0
      - pygments==2.19.1
      - pygsp==0.5.1
      - pymde==0.1.18
      - pynndescent==0.5.13
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pyreadr==0.5.3
      - pytest==8.3.5
      - python-circos==0.3.0
      - python-dotenv==1.1.0
      - python-dotplot==0.0.1
      - python-multipart==0.0.20
      - python-utils==3.9.1
      - pytoml==0.1.21
      - pytz==2025.2
      - regex==2024.11.6
      - rich==14.0.0
      - safetensors==0.5.3
      - scanpy==1.10.3
      - scikit-misc==0.3.1
      - scipy==1.11.4
      - session-info==1.0.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.46.2
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - tasklogger==1.2.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.0.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch-geometric==2.6.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.50.3
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - yarl==1.18.3
      - zope-interface==7.2

