name: scrnaseq1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scanpy=1.9.5
  - anndata=0.9.2
  - celltypist
  - pyqt=5
  - numpy=1.24
  - pandas
  - matplotlib=3.7
  - seaborn
  - scikit-learn
  - h5py
  - pip
  - pip:
    - tables
